services:
  redis:
    image: redis:7.2
    container_name: devtool_redis
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command:
      - /bin/sh
      - -c
      # - Double dollars, so that the variable is not expanded by Docker Compose
      # - Surround by quotes, so that the shell does not split the password
      # - The ${variable:?message} syntax causes shell to exit with a non-zero
      #   code and print a message, when the variable is not set or empty
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - devtool_redis:/data
  mysql:
    image: mysql:9.0
    container_name: devtool_mysql
    platform: linux/amd64
    restart: always
    volumes:
      - devtool_mysql:/var/lib/mysql
    command: --innodb_buffer_pool_size=200M
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 300M
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: devtool_phpmyadmin
    restart: always
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: ${PMA_DB_ENGINE}
      UPLOAD_LIMIT: 1000M
  mongo:
    image: mongo:8.0-rc
    container_name: devtool_mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - devtool_mongo:/data/db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 200M
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: devtool_rabbitmq
    tty: true
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_PASS: example
      RABBITMQ_DEFAULT_USER: root
    volumes:
      - devtool_rabbitmq:/var/lib/rabbitmq/mnesia/
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - devtool_postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
  zipkin:
    container_name: devtool_zipkin
    image: ghcr.io/openzipkin/zipkin-slim:latest
    ports:
      - 9411:9411

volumes:
  devtool_redis:
  devtool_mysql:
  devtool_mongo:
  devtool_rabbitmq:
  devtool_postgres:
